// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: notification.message.proto

package protom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientConnected) Reset() {
	*x = ClientConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnected) ProtoMessage() {}

func (x *ClientConnected) ProtoReflect() protoreflect.Message {
	mi := &file_notification_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnected.ProtoReflect.Descriptor instead.
func (*ClientConnected) Descriptor() ([]byte, []int) {
	return file_notification_message_proto_rawDescGZIP(), []int{0}
}

var File_notification_message_proto protoreflect.FileDescriptor

var file_notification_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x42, 0x34, 0x5a,
	0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73, 0x74,
	0x6a, 0x61, 0x63, 0x6b, 0x31, 0x35, 0x32, 0x31, 0x2f, 0x6d, 0x65, 0x76, 0x69, 0x75, 0x6d, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notification_message_proto_rawDescOnce sync.Once
	file_notification_message_proto_rawDescData = file_notification_message_proto_rawDesc
)

func file_notification_message_proto_rawDescGZIP() []byte {
	file_notification_message_proto_rawDescOnce.Do(func() {
		file_notification_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_notification_message_proto_rawDescData)
	})
	return file_notification_message_proto_rawDescData
}

var file_notification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notification_message_proto_goTypes = []interface{}{
	(*ClientConnected)(nil), // 0: notification.ClientConnected
}
var file_notification_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_message_proto_init() }
func file_notification_message_proto_init() {
	if File_notification_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notification_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notification_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_message_proto_goTypes,
		DependencyIndexes: file_notification_message_proto_depIdxs,
		MessageInfos:      file_notification_message_proto_msgTypes,
	}.Build()
	File_notification_message_proto = out.File
	file_notification_message_proto_rawDesc = nil
	file_notification_message_proto_goTypes = nil
	file_notification_message_proto_depIdxs = nil
}
