// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: protorank/rank.response.proto

package protorank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitScoreResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WeeklyRankUpdate    *ProtoRankingInfo      `protobuf:"bytes,1,opt,name=weekly_rank_update,json=weeklyRankUpdate,proto3" json:"weekly_rank_update,omitempty"`
	EventRankUpdate     *ProtoRankingInfo      `protobuf:"bytes,2,opt,name=event_rank_update,json=eventRankUpdate,proto3" json:"event_rank_update,omitempty"`
	WeeklyHighScore     bool                   `protobuf:"varint,3,opt,name=weekly_high_score,json=weeklyHighScore,proto3" json:"weekly_high_score,omitempty"`
	EventHighScore      bool                   `protobuf:"varint,4,opt,name=event_high_score,json=eventHighScore,proto3" json:"event_high_score,omitempty"`
	CurrentWeeklyScore  float64                `protobuf:"fixed64,5,opt,name=current_weekly_score,json=currentWeeklyScore,proto3" json:"current_weekly_score,omitempty"`
	PreviousWeeklyScore float64                `protobuf:"fixed64,6,opt,name=previous_weekly_score,json=previousWeeklyScore,proto3" json:"previous_weekly_score,omitempty"`
	CurrentEventScore   float64                `protobuf:"fixed64,7,opt,name=current_event_score,json=currentEventScore,proto3" json:"current_event_score,omitempty"`
	PreviousEventScore  float64                `protobuf:"fixed64,8,opt,name=previous_event_score,json=previousEventScore,proto3" json:"previous_event_score,omitempty"`
	PreviousWeeklyRank  int64                  `protobuf:"varint,9,opt,name=previous_weekly_rank,json=previousWeeklyRank,proto3" json:"previous_weekly_rank,omitempty"`
	PreviouslyEventRank int64                  `protobuf:"varint,10,opt,name=previously_event_rank,json=previouslyEventRank,proto3" json:"previously_event_rank,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubmitScoreResponse) Reset() {
	*x = SubmitScoreResponse{}
	mi := &file_protorank_rank_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreResponse) ProtoMessage() {}

func (x *SubmitScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protorank_rank_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreResponse.ProtoReflect.Descriptor instead.
func (*SubmitScoreResponse) Descriptor() ([]byte, []int) {
	return file_protorank_rank_response_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitScoreResponse) GetWeeklyRankUpdate() *ProtoRankingInfo {
	if x != nil {
		return x.WeeklyRankUpdate
	}
	return nil
}

func (x *SubmitScoreResponse) GetEventRankUpdate() *ProtoRankingInfo {
	if x != nil {
		return x.EventRankUpdate
	}
	return nil
}

func (x *SubmitScoreResponse) GetWeeklyHighScore() bool {
	if x != nil {
		return x.WeeklyHighScore
	}
	return false
}

func (x *SubmitScoreResponse) GetEventHighScore() bool {
	if x != nil {
		return x.EventHighScore
	}
	return false
}

func (x *SubmitScoreResponse) GetCurrentWeeklyScore() float64 {
	if x != nil {
		return x.CurrentWeeklyScore
	}
	return 0
}

func (x *SubmitScoreResponse) GetPreviousWeeklyScore() float64 {
	if x != nil {
		return x.PreviousWeeklyScore
	}
	return 0
}

func (x *SubmitScoreResponse) GetCurrentEventScore() float64 {
	if x != nil {
		return x.CurrentEventScore
	}
	return 0
}

func (x *SubmitScoreResponse) GetPreviousEventScore() float64 {
	if x != nil {
		return x.PreviousEventScore
	}
	return 0
}

func (x *SubmitScoreResponse) GetPreviousWeeklyRank() int64 {
	if x != nil {
		return x.PreviousWeeklyRank
	}
	return 0
}

func (x *SubmitScoreResponse) GetPreviouslyEventRank() int64 {
	if x != nil {
		return x.PreviouslyEventRank
	}
	return 0
}

type RefreshWeeklyRankRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankRanges    *ProtoRankingInfo      `protobuf:"bytes,1,opt,name=rank_ranges,json=rankRanges,proto3" json:"rank_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshWeeklyRankRangeResponse) Reset() {
	*x = RefreshWeeklyRankRangeResponse{}
	mi := &file_protorank_rank_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshWeeklyRankRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshWeeklyRankRangeResponse) ProtoMessage() {}

func (x *RefreshWeeklyRankRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protorank_rank_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshWeeklyRankRangeResponse.ProtoReflect.Descriptor instead.
func (*RefreshWeeklyRankRangeResponse) Descriptor() ([]byte, []int) {
	return file_protorank_rank_response_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshWeeklyRankRangeResponse) GetRankRanges() *ProtoRankingInfo {
	if x != nil {
		return x.RankRanges
	}
	return nil
}

type RefreshSpecialRankRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankRanges    *ProtoRankingInfo      `protobuf:"bytes,1,opt,name=rank_ranges,json=rankRanges,proto3" json:"rank_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSpecialRankRangeResponse) Reset() {
	*x = RefreshSpecialRankRangeResponse{}
	mi := &file_protorank_rank_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSpecialRankRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSpecialRankRangeResponse) ProtoMessage() {}

func (x *RefreshSpecialRankRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protorank_rank_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSpecialRankRangeResponse.ProtoReflect.Descriptor instead.
func (*RefreshSpecialRankRangeResponse) Descriptor() ([]byte, []int) {
	return file_protorank_rank_response_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshSpecialRankRangeResponse) GetRankRanges() *ProtoRankingInfo {
	if x != nil {
		return x.RankRanges
	}
	return nil
}

type GetTopRankResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Rankings      []*ProtoPlayerRankSetDetails `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopRankResponse) Reset() {
	*x = GetTopRankResponse{}
	mi := &file_protorank_rank_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRankResponse) ProtoMessage() {}

func (x *GetTopRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protorank_rank_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRankResponse.ProtoReflect.Descriptor instead.
func (*GetTopRankResponse) Descriptor() ([]byte, []int) {
	return file_protorank_rank_response_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopRankResponse) GetRankings() []*ProtoPlayerRankSetDetails {
	if x != nil {
		return x.Rankings
	}
	return nil
}

var File_protorank_rank_response_proto protoreflect.FileDescriptor

const file_protorank_rank_response_proto_rawDesc = "" +
	"\n" +
	"\x1dprotorank/rank.response.proto\x12\x04rank\x1a\x14protorank/rank.proto\"\xa3\x04\n" +
	"\x13SubmitScoreResponse\x12D\n" +
	"\x12weekly_rank_update\x18\x01 \x01(\v2\x16.rank.ProtoRankingInfoR\x10weeklyRankUpdate\x12B\n" +
	"\x11event_rank_update\x18\x02 \x01(\v2\x16.rank.ProtoRankingInfoR\x0feventRankUpdate\x12*\n" +
	"\x11weekly_high_score\x18\x03 \x01(\bR\x0fweeklyHighScore\x12(\n" +
	"\x10event_high_score\x18\x04 \x01(\bR\x0eeventHighScore\x120\n" +
	"\x14current_weekly_score\x18\x05 \x01(\x01R\x12currentWeeklyScore\x122\n" +
	"\x15previous_weekly_score\x18\x06 \x01(\x01R\x13previousWeeklyScore\x12.\n" +
	"\x13current_event_score\x18\a \x01(\x01R\x11currentEventScore\x120\n" +
	"\x14previous_event_score\x18\b \x01(\x01R\x12previousEventScore\x120\n" +
	"\x14previous_weekly_rank\x18\t \x01(\x03R\x12previousWeeklyRank\x122\n" +
	"\x15previously_event_rank\x18\n" +
	" \x01(\x03R\x13previouslyEventRank\"Y\n" +
	"\x1eRefreshWeeklyRankRangeResponse\x127\n" +
	"\vrank_ranges\x18\x01 \x01(\v2\x16.rank.ProtoRankingInfoR\n" +
	"rankRanges\"Z\n" +
	"\x1fRefreshSpecialRankRangeResponse\x127\n" +
	"\vrank_ranges\x18\x01 \x01(\v2\x16.rank.ProtoRankingInfoR\n" +
	"rankRanges\"Q\n" +
	"\x12GetTopRankResponse\x12;\n" +
	"\brankings\x18\x01 \x03(\v2\x1f.rank.ProtoPlayerRankSetDetailsR\brankingsBKZ5github.com/justjack1521/mevium/pkg/genproto/protorank\xaa\x02\x11Mobius.Proto.Rankb\x06proto3"

var (
	file_protorank_rank_response_proto_rawDescOnce sync.Once
	file_protorank_rank_response_proto_rawDescData []byte
)

func file_protorank_rank_response_proto_rawDescGZIP() []byte {
	file_protorank_rank_response_proto_rawDescOnce.Do(func() {
		file_protorank_rank_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protorank_rank_response_proto_rawDesc), len(file_protorank_rank_response_proto_rawDesc)))
	})
	return file_protorank_rank_response_proto_rawDescData
}

var file_protorank_rank_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protorank_rank_response_proto_goTypes = []any{
	(*SubmitScoreResponse)(nil),             // 0: rank.SubmitScoreResponse
	(*RefreshWeeklyRankRangeResponse)(nil),  // 1: rank.RefreshWeeklyRankRangeResponse
	(*RefreshSpecialRankRangeResponse)(nil), // 2: rank.RefreshSpecialRankRangeResponse
	(*GetTopRankResponse)(nil),              // 3: rank.GetTopRankResponse
	(*ProtoRankingInfo)(nil),                // 4: rank.ProtoRankingInfo
	(*ProtoPlayerRankSetDetails)(nil),       // 5: rank.ProtoPlayerRankSetDetails
}
var file_protorank_rank_response_proto_depIdxs = []int32{
	4, // 0: rank.SubmitScoreResponse.weekly_rank_update:type_name -> rank.ProtoRankingInfo
	4, // 1: rank.SubmitScoreResponse.event_rank_update:type_name -> rank.ProtoRankingInfo
	4, // 2: rank.RefreshWeeklyRankRangeResponse.rank_ranges:type_name -> rank.ProtoRankingInfo
	4, // 3: rank.RefreshSpecialRankRangeResponse.rank_ranges:type_name -> rank.ProtoRankingInfo
	5, // 4: rank.GetTopRankResponse.rankings:type_name -> rank.ProtoPlayerRankSetDetails
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protorank_rank_response_proto_init() }
func file_protorank_rank_response_proto_init() {
	if File_protorank_rank_response_proto != nil {
		return
	}
	file_protorank_rank_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protorank_rank_response_proto_rawDesc), len(file_protorank_rank_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protorank_rank_response_proto_goTypes,
		DependencyIndexes: file_protorank_rank_response_proto_depIdxs,
		MessageInfos:      file_protorank_rank_response_proto_msgTypes,
	}.Build()
	File_protorank_rank_response_proto = out.File
	file_protorank_rank_response_proto_goTypes = nil
	file_protorank_rank_response_proto_depIdxs = nil
}
