// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: protoadmin/response.proto

package protoadmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemResponse) Reset() {
	*x = GrantItemResponse{}
	mi := &file_protoadmin_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemResponse) ProtoMessage() {}

func (x *GrantItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoadmin_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemResponse.ProtoReflect.Descriptor instead.
func (*GrantItemResponse) Descriptor() ([]byte, []int) {
	return file_protoadmin_response_proto_rawDescGZIP(), []int{0}
}

type CreateSkillPanelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillPanelResponse) Reset() {
	*x = CreateSkillPanelResponse{}
	mi := &file_protoadmin_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillPanelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillPanelResponse) ProtoMessage() {}

func (x *CreateSkillPanelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoadmin_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillPanelResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillPanelResponse) Descriptor() ([]byte, []int) {
	return file_protoadmin_response_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkillPanelResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type CreateBaseJobCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBaseJobCardResponse) Reset() {
	*x = CreateBaseJobCardResponse{}
	mi := &file_protoadmin_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBaseJobCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseJobCardResponse) ProtoMessage() {}

func (x *CreateBaseJobCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoadmin_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseJobCardResponse.ProtoReflect.Descriptor instead.
func (*CreateBaseJobCardResponse) Descriptor() ([]byte, []int) {
	return file_protoadmin_response_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBaseJobCardResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type CreateAugmentMaterialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAugmentMaterialsResponse) Reset() {
	*x = CreateAugmentMaterialsResponse{}
	mi := &file_protoadmin_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAugmentMaterialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAugmentMaterialsResponse) ProtoMessage() {}

func (x *CreateAugmentMaterialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoadmin_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAugmentMaterialsResponse.ProtoReflect.Descriptor instead.
func (*CreateAugmentMaterialsResponse) Descriptor() ([]byte, []int) {
	return file_protoadmin_response_proto_rawDescGZIP(), []int{3}
}

type CreateBaseCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBaseCardResponse) Reset() {
	*x = CreateBaseCardResponse{}
	mi := &file_protoadmin_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBaseCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseCardResponse) ProtoMessage() {}

func (x *CreateBaseCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoadmin_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseCardResponse.ProtoReflect.Descriptor instead.
func (*CreateBaseCardResponse) Descriptor() ([]byte, []int) {
	return file_protoadmin_response_proto_rawDescGZIP(), []int{4}
}

type CreateAbilityCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAbilityCardResponse) Reset() {
	*x = CreateAbilityCardResponse{}
	mi := &file_protoadmin_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAbilityCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAbilityCardResponse) ProtoMessage() {}

func (x *CreateAbilityCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoadmin_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAbilityCardResponse.ProtoReflect.Descriptor instead.
func (*CreateAbilityCardResponse) Descriptor() ([]byte, []int) {
	return file_protoadmin_response_proto_rawDescGZIP(), []int{5}
}

var File_protoadmin_response_proto protoreflect.FileDescriptor

const file_protoadmin_response_proto_rawDesc = "" +
	"\n" +
	"\x19protoadmin/response.proto\x12\x05admin\"\x13\n" +
	"\x11GrantItemResponse\"4\n" +
	"\x18CreateSkillPanelResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\"5\n" +
	"\x19CreateBaseJobCardResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\" \n" +
	"\x1eCreateAugmentMaterialsResponse\"\x18\n" +
	"\x16CreateBaseCardResponse\"\x1b\n" +
	"\x19CreateAbilityCardResponseB8Z6github.com/justjack1521/mevium/pkg/genproto/protoadminb\x06proto3"

var (
	file_protoadmin_response_proto_rawDescOnce sync.Once
	file_protoadmin_response_proto_rawDescData []byte
)

func file_protoadmin_response_proto_rawDescGZIP() []byte {
	file_protoadmin_response_proto_rawDescOnce.Do(func() {
		file_protoadmin_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoadmin_response_proto_rawDesc), len(file_protoadmin_response_proto_rawDesc)))
	})
	return file_protoadmin_response_proto_rawDescData
}

var file_protoadmin_response_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protoadmin_response_proto_goTypes = []any{
	(*GrantItemResponse)(nil),              // 0: admin.GrantItemResponse
	(*CreateSkillPanelResponse)(nil),       // 1: admin.CreateSkillPanelResponse
	(*CreateBaseJobCardResponse)(nil),      // 2: admin.CreateBaseJobCardResponse
	(*CreateAugmentMaterialsResponse)(nil), // 3: admin.CreateAugmentMaterialsResponse
	(*CreateBaseCardResponse)(nil),         // 4: admin.CreateBaseCardResponse
	(*CreateAbilityCardResponse)(nil),      // 5: admin.CreateAbilityCardResponse
}
var file_protoadmin_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoadmin_response_proto_init() }
func file_protoadmin_response_proto_init() {
	if File_protoadmin_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoadmin_response_proto_rawDesc), len(file_protoadmin_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoadmin_response_proto_goTypes,
		DependencyIndexes: file_protoadmin_response_proto_depIdxs,
		MessageInfos:      file_protoadmin_response_proto_msgTypes,
	}.Build()
	File_protoadmin_response_proto = out.File
	file_protoadmin_response_proto_goTypes = nil
	file_protoadmin_response_proto_depIdxs = nil
}
