// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: game.response.proto

package protoc

import (
	protog "github.com/justjack1521/mevium/pkg/genproto/protog"
	protor "github.com/justjack1521/mevium/pkg/genproto/protor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode    int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ApplicationError) Reset() {
	*x = ApplicationError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationError) ProtoMessage() {}

func (x *ApplicationError) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationError.ProtoReflect.Descriptor instead.
func (*ApplicationError) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationError) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ApplicationError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []byte          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId     string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	CommandId    string `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Operation    int32  `protobuf:"varint,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Error        bool   `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode    int32  `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseHeader) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ResponseHeader) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ResponseHeader) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ResponseHeader) GetOperation() int32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *ResponseHeader) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseHeader) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ResponseHeader) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BattleCompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results             *protog.ProtoLastBattleResults     `protobuf:"bytes,1,opt,name=Results,proto3" json:"Results,omitempty"`
	SeedRewards         []*protog.ProtoItemValuePair       `protobuf:"bytes,4,rep,name=seed_rewards,json=seedRewards,proto3" json:"seed_rewards,omitempty"`
	SeedAreaMultiplier  float32                            `protobuf:"fixed32,5,opt,name=seed_area_multiplier,json=seedAreaMultiplier,proto3" json:"seed_area_multiplier,omitempty"`
	SeedScoreMultiplier float32                            `protobuf:"fixed32,6,opt,name=seed_score_multiplier,json=seedScoreMultiplier,proto3" json:"seed_score_multiplier,omitempty"`
	ItemRewards         []*protog.ProtoItemValuePair       `protobuf:"bytes,7,rep,name=item_rewards,json=itemRewards,proto3" json:"item_rewards,omitempty"`
	CardDrops           []*protog.ProtoAbilityCardInstance `protobuf:"bytes,8,rep,name=card_drops,json=cardDrops,proto3" json:"card_drops,omitempty"`
	PendingEvents       bool                               `protobuf:"varint,9,opt,name=pending_events,json=pendingEvents,proto3" json:"pending_events,omitempty"`
	WeeklyRankUpdate    *protor.ProtoRankingInfo           `protobuf:"bytes,10,opt,name=weekly_rank_update,json=weeklyRankUpdate,proto3" json:"weekly_rank_update,omitempty"`
	EventRankUpdate     *protor.ProtoRankingInfo           `protobuf:"bytes,11,opt,name=event_rank_update,json=eventRankUpdate,proto3" json:"event_rank_update,omitempty"`
}

func (x *BattleCompleteResponse) Reset() {
	*x = BattleCompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleCompleteResponse) ProtoMessage() {}

func (x *BattleCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleCompleteResponse.ProtoReflect.Descriptor instead.
func (*BattleCompleteResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{3}
}

func (x *BattleCompleteResponse) GetResults() *protog.ProtoLastBattleResults {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BattleCompleteResponse) GetSeedRewards() []*protog.ProtoItemValuePair {
	if x != nil {
		return x.SeedRewards
	}
	return nil
}

func (x *BattleCompleteResponse) GetSeedAreaMultiplier() float32 {
	if x != nil {
		return x.SeedAreaMultiplier
	}
	return 0
}

func (x *BattleCompleteResponse) GetSeedScoreMultiplier() float32 {
	if x != nil {
		return x.SeedScoreMultiplier
	}
	return 0
}

func (x *BattleCompleteResponse) GetItemRewards() []*protog.ProtoItemValuePair {
	if x != nil {
		return x.ItemRewards
	}
	return nil
}

func (x *BattleCompleteResponse) GetCardDrops() []*protog.ProtoAbilityCardInstance {
	if x != nil {
		return x.CardDrops
	}
	return nil
}

func (x *BattleCompleteResponse) GetPendingEvents() bool {
	if x != nil {
		return x.PendingEvents
	}
	return false
}

func (x *BattleCompleteResponse) GetWeeklyRankUpdate() *protor.ProtoRankingInfo {
	if x != nil {
		return x.WeeklyRankUpdate
	}
	return nil
}

func (x *BattleCompleteResponse) GetEventRankUpdate() *protor.ProtoRankingInfo {
	if x != nil {
		return x.EventRankUpdate
	}
	return nil
}

type BattleReviveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemRemoved *protog.ProtoItemValuePair `protobuf:"bytes,1,opt,name=ItemRemoved,proto3" json:"ItemRemoved,omitempty"`
}

func (x *BattleReviveResponse) Reset() {
	*x = BattleReviveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleReviveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleReviveResponse) ProtoMessage() {}

func (x *BattleReviveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleReviveResponse.ProtoReflect.Descriptor instead.
func (*BattleReviveResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{4}
}

func (x *BattleReviveResponse) GetItemRemoved() *protog.ProtoItemValuePair {
	if x != nil {
		return x.ItemRemoved
	}
	return nil
}

type BattleStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleStartData  *protog.ProtoBattleStartData `protobuf:"bytes,1,opt,name=BattleStartData,proto3" json:"BattleStartData,omitempty"`
	StaminaDecreased uint32                       `protobuf:"varint,2,opt,name=stamina_decreased,json=staminaDecreased,proto3" json:"stamina_decreased,omitempty"`
	StaminaDec       uint64                       `protobuf:"varint,3,opt,name=stamina_dec,json=staminaDec,proto3" json:"stamina_dec,omitempty"`
}

func (x *BattleStartResponse) Reset() {
	*x = BattleStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStartResponse) ProtoMessage() {}

func (x *BattleStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStartResponse.ProtoReflect.Descriptor instead.
func (*BattleStartResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{5}
}

func (x *BattleStartResponse) GetBattleStartData() *protog.ProtoBattleStartData {
	if x != nil {
		return x.BattleStartData
	}
	return nil
}

func (x *BattleStartResponse) GetStaminaDecreased() uint32 {
	if x != nil {
		return x.StaminaDecreased
	}
	return 0
}

func (x *BattleStartResponse) GetStaminaDec() uint64 {
	if x != nil {
		return x.StaminaDec
	}
	return 0
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameData []byte `protobuf:"bytes,1,opt,name=game_data,json=gameData,proto3" json:"game_data,omitempty"`
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProfileResponse) GetGameData() []byte {
	if x != nil {
		return x.GameData
	}
	return nil
}

type CardAugmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CardAugmentResponse) Reset() {
	*x = CardAugmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardAugmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAugmentResponse) ProtoMessage() {}

func (x *CardAugmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAugmentResponse.ProtoReflect.Descriptor instead.
func (*CardAugmentResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{7}
}

type CardFavouriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId string `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Locked bool   `protobuf:"varint,2,opt,name=locked,proto3" json:"locked,omitempty"`
}

func (x *CardFavouriteResponse) Reset() {
	*x = CardFavouriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardFavouriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardFavouriteResponse) ProtoMessage() {}

func (x *CardFavouriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardFavouriteResponse.ProtoReflect.Descriptor instead.
func (*CardFavouriteResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{8}
}

func (x *CardFavouriteResponse) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardFavouriteResponse) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

type CardFusionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId                string                     `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CardLevel             int32                      `protobuf:"varint,2,opt,name=card_level,json=cardLevel,proto3" json:"card_level,omitempty"`
	CardTotalExp          uint64                     `protobuf:"varint,3,opt,name=card_total_exp,json=cardTotalExp,proto3" json:"card_total_exp,omitempty"`
	CardAccumExp          uint64                     `protobuf:"varint,4,opt,name=card_accum_exp,json=cardAccumExp,proto3" json:"card_accum_exp,omitempty"`
	SeedLevelGain         int32                      `protobuf:"varint,5,opt,name=seed_level_gain,json=seedLevelGain,proto3" json:"seed_level_gain,omitempty"`
	AbilityLevelGain      int32                      `protobuf:"varint,6,opt,name=ability_level_gain,json=abilityLevelGain,proto3" json:"ability_level_gain,omitempty"`
	InventoryCardsRemoved []string                   `protobuf:"bytes,7,rep,name=inventory_cards_removed,json=inventoryCardsRemoved,proto3" json:"inventory_cards_removed,omitempty"`
	BankCardsRemoved      []string                   `protobuf:"bytes,8,rep,name=bank_cards_removed,json=bankCardsRemoved,proto3" json:"bank_cards_removed,omitempty"`
	FusionCost            *protog.ProtoItemValuePair `protobuf:"bytes,9,opt,name=fusion_cost,json=fusionCost,proto3" json:"fusion_cost,omitempty"`
}

func (x *CardFusionResponse) Reset() {
	*x = CardFusionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardFusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardFusionResponse) ProtoMessage() {}

func (x *CardFusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardFusionResponse.ProtoReflect.Descriptor instead.
func (*CardFusionResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{9}
}

func (x *CardFusionResponse) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardFusionResponse) GetCardLevel() int32 {
	if x != nil {
		return x.CardLevel
	}
	return 0
}

func (x *CardFusionResponse) GetCardTotalExp() uint64 {
	if x != nil {
		return x.CardTotalExp
	}
	return 0
}

func (x *CardFusionResponse) GetCardAccumExp() uint64 {
	if x != nil {
		return x.CardAccumExp
	}
	return 0
}

func (x *CardFusionResponse) GetSeedLevelGain() int32 {
	if x != nil {
		return x.SeedLevelGain
	}
	return 0
}

func (x *CardFusionResponse) GetAbilityLevelGain() int32 {
	if x != nil {
		return x.AbilityLevelGain
	}
	return 0
}

func (x *CardFusionResponse) GetInventoryCardsRemoved() []string {
	if x != nil {
		return x.InventoryCardsRemoved
	}
	return nil
}

func (x *CardFusionResponse) GetBankCardsRemoved() []string {
	if x != nil {
		return x.BankCardsRemoved
	}
	return nil
}

func (x *CardFusionResponse) GetFusionCost() *protog.ProtoItemValuePair {
	if x != nil {
		return x.FusionCost
	}
	return nil
}

type CardBoostFusionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId           string                     `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	SeedLevelGain    int32                      `protobuf:"varint,2,opt,name=seed_level_gain,json=seedLevelGain,proto3" json:"seed_level_gain,omitempty"`
	AbilityLevelGain int32                      `protobuf:"varint,3,opt,name=ability_level_gain,json=abilityLevelGain,proto3" json:"ability_level_gain,omitempty"`
	FusionCost       *protog.ProtoItemValuePair `protobuf:"bytes,4,opt,name=fusion_cost,json=fusionCost,proto3" json:"fusion_cost,omitempty"`
}

func (x *CardBoostFusionResponse) Reset() {
	*x = CardBoostFusionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardBoostFusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardBoostFusionResponse) ProtoMessage() {}

func (x *CardBoostFusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardBoostFusionResponse.ProtoReflect.Descriptor instead.
func (*CardBoostFusionResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{10}
}

func (x *CardBoostFusionResponse) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardBoostFusionResponse) GetSeedLevelGain() int32 {
	if x != nil {
		return x.SeedLevelGain
	}
	return 0
}

func (x *CardBoostFusionResponse) GetAbilityLevelGain() int32 {
	if x != nil {
		return x.AbilityLevelGain
	}
	return 0
}

func (x *CardBoostFusionResponse) GetFusionCost() *protog.ProtoItemValuePair {
	if x != nil {
		return x.FusionCost
	}
	return nil
}

type CardSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalGold    int32    `protobuf:"varint,1,opt,name=total_gold,json=totalGold,proto3" json:"total_gold,omitempty"`
	CardsRemoved []string `protobuf:"bytes,2,rep,name=cards_removed,json=cardsRemoved,proto3" json:"cards_removed,omitempty"`
}

func (x *CardSaleResponse) Reset() {
	*x = CardSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardSaleResponse) ProtoMessage() {}

func (x *CardSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardSaleResponse.ProtoReflect.Descriptor instead.
func (*CardSaleResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{11}
}

func (x *CardSaleResponse) GetTotalGold() int32 {
	if x != nil {
		return x.TotalGold
	}
	return 0
}

func (x *CardSaleResponse) GetCardsRemoved() []string {
	if x != nil {
		return x.CardsRemoved
	}
	return nil
}

type CardTransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CardTransferResponse) Reset() {
	*x = CardTransferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardTransferResponse) ProtoMessage() {}

func (x *CardTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardTransferResponse.ProtoReflect.Descriptor instead.
func (*CardTransferResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{12}
}

type ClaimLoginCampaignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claim *protog.ProtoMailBoxItem `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
}

func (x *ClaimLoginCampaignResponse) Reset() {
	*x = ClaimLoginCampaignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimLoginCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimLoginCampaignResponse) ProtoMessage() {}

func (x *ClaimLoginCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimLoginCampaignResponse.ProtoReflect.Descriptor instead.
func (*ClaimLoginCampaignResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{13}
}

func (x *ClaimLoginCampaignResponse) GetClaim() *protog.ProtoMailBoxItem {
	if x != nil {
		return x.Claim
	}
	return nil
}

type ClaimMailBoxItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claim *protog.ProtoMailBoxItem `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
}

func (x *ClaimMailBoxItemResponse) Reset() {
	*x = ClaimMailBoxItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimMailBoxItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMailBoxItemResponse) ProtoMessage() {}

func (x *ClaimMailBoxItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMailBoxItemResponse.ProtoReflect.Descriptor instead.
func (*ClaimMailBoxItemResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{14}
}

func (x *ClaimMailBoxItemResponse) GetClaim() *protog.ProtoMailBoxItem {
	if x != nil {
		return x.Claim
	}
	return nil
}

type ClaimAllMailBoxItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claims []*protog.ProtoMailBoxItem `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
}

func (x *ClaimAllMailBoxItemResponse) Reset() {
	*x = ClaimAllMailBoxItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimAllMailBoxItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAllMailBoxItemResponse) ProtoMessage() {}

func (x *ClaimAllMailBoxItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAllMailBoxItemResponse.ProtoReflect.Descriptor instead.
func (*ClaimAllMailBoxItemResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{15}
}

func (x *ClaimAllMailBoxItemResponse) GetClaims() []*protog.ProtoMailBoxItem {
	if x != nil {
		return x.Claims
	}
	return nil
}

type DeleteAllMailboxItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAllMailboxItemResponse) Reset() {
	*x = DeleteAllMailboxItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAllMailboxItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllMailboxItemResponse) ProtoMessage() {}

func (x *DeleteAllMailboxItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllMailboxItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteAllMailboxItemResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{16}
}

type ClaimEventRankingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claims []*protog.ProtoMailBoxItem `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
}

func (x *ClaimEventRankingResponse) Reset() {
	*x = ClaimEventRankingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimEventRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimEventRankingResponse) ProtoMessage() {}

func (x *ClaimEventRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimEventRankingResponse.ProtoReflect.Descriptor instead.
func (*ClaimEventRankingResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{17}
}

func (x *ClaimEventRankingResponse) GetClaims() []*protog.ProtoMailBoxItem {
	if x != nil {
		return x.Claims
	}
	return nil
}

type ClaimRentalCardRewardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardItem *protog.ProtoItemValuePair `protobuf:"bytes,1,opt,name=reward_item,json=rewardItem,proto3" json:"reward_item,omitempty"`
}

func (x *ClaimRentalCardRewardResponse) Reset() {
	*x = ClaimRentalCardRewardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimRentalCardRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRentalCardRewardResponse) ProtoMessage() {}

func (x *ClaimRentalCardRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRentalCardRewardResponse.ProtoReflect.Descriptor instead.
func (*ClaimRentalCardRewardResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{18}
}

func (x *ClaimRentalCardRewardResponse) GetRewardItem() *protog.ProtoItemValuePair {
	if x != nil {
		return x.RewardItem
	}
	return nil
}

type ConfirmDailyMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmDailyMissionResponse) Reset() {
	*x = ConfirmDailyMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmDailyMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDailyMissionResponse) ProtoMessage() {}

func (x *ConfirmDailyMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDailyMissionResponse.ProtoReflect.Descriptor instead.
func (*ConfirmDailyMissionResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{19}
}

type DeckEditAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection  *protog.ProtoPlayerDeckCollection `protobuf:"bytes,1,opt,name=Collection,proto3" json:"Collection,omitempty"`
	MultiPlayer bool                              `protobuf:"varint,2,opt,name=MultiPlayer,proto3" json:"MultiPlayer,omitempty"`
}

func (x *DeckEditAllResponse) Reset() {
	*x = DeckEditAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckEditAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckEditAllResponse) ProtoMessage() {}

func (x *DeckEditAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckEditAllResponse.ProtoReflect.Descriptor instead.
func (*DeckEditAllResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{20}
}

func (x *DeckEditAllResponse) GetCollection() *protog.ProtoPlayerDeckCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *DeckEditAllResponse) GetMultiPlayer() bool {
	if x != nil {
		return x.MultiPlayer
	}
	return false
}

type FetchPlayerDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *protog.ProtoGameData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FetchPlayerDataResponse) Reset() {
	*x = FetchPlayerDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPlayerDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPlayerDataResponse) ProtoMessage() {}

func (x *FetchPlayerDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPlayerDataResponse.ProtoReflect.Descriptor instead.
func (*FetchPlayerDataResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{21}
}

func (x *FetchPlayerDataResponse) GetData() *protog.ProtoGameData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FirstDailyLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginBonusReceived int64                              `protobuf:"varint,1,opt,name=login_bonus_received,json=loginBonusReceived,proto3" json:"login_bonus_received,omitempty"`
	DailyMission       *protog.ProtoDailyMissionInstance  `protobuf:"bytes,2,opt,name=daily_mission,json=dailyMission,proto3" json:"daily_mission,omitempty"`
	StandardLoginBonus *protog.ProtoLoginCampaignInstance `protobuf:"bytes,3,opt,name=standard_login_bonus,json=standardLoginBonus,proto3" json:"standard_login_bonus,omitempty"`
	SpecialLoginBonus  *protog.ProtoLoginCampaignInstance `protobuf:"bytes,4,opt,name=special_login_bonus,json=specialLoginBonus,proto3" json:"special_login_bonus,omitempty"`
	RentalCount        int32                              `protobuf:"varint,5,opt,name=rental_count,json=rentalCount,proto3" json:"rental_count,omitempty"`
	RentalClaim        bool                               `protobuf:"varint,6,opt,name=rental_claim,json=rentalClaim,proto3" json:"rental_claim,omitempty"`
}

func (x *FirstDailyLoginResponse) Reset() {
	*x = FirstDailyLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FirstDailyLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstDailyLoginResponse) ProtoMessage() {}

func (x *FirstDailyLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstDailyLoginResponse.ProtoReflect.Descriptor instead.
func (*FirstDailyLoginResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{22}
}

func (x *FirstDailyLoginResponse) GetLoginBonusReceived() int64 {
	if x != nil {
		return x.LoginBonusReceived
	}
	return 0
}

func (x *FirstDailyLoginResponse) GetDailyMission() *protog.ProtoDailyMissionInstance {
	if x != nil {
		return x.DailyMission
	}
	return nil
}

func (x *FirstDailyLoginResponse) GetStandardLoginBonus() *protog.ProtoLoginCampaignInstance {
	if x != nil {
		return x.StandardLoginBonus
	}
	return nil
}

func (x *FirstDailyLoginResponse) GetSpecialLoginBonus() *protog.ProtoLoginCampaignInstance {
	if x != nil {
		return x.SpecialLoginBonus
	}
	return nil
}

func (x *FirstDailyLoginResponse) GetRentalCount() int32 {
	if x != nil {
		return x.RentalCount
	}
	return 0
}

func (x *FirstDailyLoginResponse) GetRentalClaim() bool {
	if x != nil {
		return x.RentalClaim
	}
	return false
}

type FilterSortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View       int32                       `protobuf:"varint,1,opt,name=View,proto3" json:"View,omitempty"`
	Index      int32                       `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	FilterSort *protog.ProtoCardFilterSort `protobuf:"bytes,3,opt,name=FilterSort,proto3" json:"FilterSort,omitempty"`
}

func (x *FilterSortResponse) Reset() {
	*x = FilterSortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterSortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterSortResponse) ProtoMessage() {}

func (x *FilterSortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterSortResponse.ProtoReflect.Descriptor instead.
func (*FilterSortResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{23}
}

func (x *FilterSortResponse) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *FilterSortResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FilterSortResponse) GetFilterSort() *protog.ProtoCardFilterSort {
	if x != nil {
		return x.FilterSort
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanionId string `protobuf:"bytes,1,opt,name=companion_id,json=companionId,proto3" json:"companion_id,omitempty"`
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateProfileResponse) GetCompanionId() string {
	if x != nil {
		return x.CompanionId
	}
	return ""
}

type StaminaRestoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId        string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemAmount    int32  `protobuf:"varint,2,opt,name=item_amount,json=itemAmount,proto3" json:"item_amount,omitempty"`
	RestoreAmount int32  `protobuf:"varint,3,opt,name=restore_amount,json=restoreAmount,proto3" json:"restore_amount,omitempty"`
}

func (x *StaminaRestoreResponse) Reset() {
	*x = StaminaRestoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaminaRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaminaRestoreResponse) ProtoMessage() {}

func (x *StaminaRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaminaRestoreResponse.ProtoReflect.Descriptor instead.
func (*StaminaRestoreResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{25}
}

func (x *StaminaRestoreResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *StaminaRestoreResponse) GetItemAmount() int32 {
	if x != nil {
		return x.ItemAmount
	}
	return 0
}

func (x *StaminaRestoreResponse) GetRestoreAmount() int32 {
	if x != nil {
		return x.RestoreAmount
	}
	return 0
}

type SkillPanelUnlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobCardIndex         int32 `protobuf:"varint,1,opt,name=JobCardIndex,proto3" json:"JobCardIndex,omitempty"`
	SkillPanelGroupIndex int32 `protobuf:"varint,2,opt,name=SkillPanelGroupIndex,proto3" json:"SkillPanelGroupIndex,omitempty"`
	SkillPanelIndex      int32 `protobuf:"varint,3,opt,name=SkillPanelIndex,proto3" json:"SkillPanelIndex,omitempty"`
}

func (x *SkillPanelUnlockRequest) Reset() {
	*x = SkillPanelUnlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillPanelUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillPanelUnlockRequest) ProtoMessage() {}

func (x *SkillPanelUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillPanelUnlockRequest.ProtoReflect.Descriptor instead.
func (*SkillPanelUnlockRequest) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{26}
}

func (x *SkillPanelUnlockRequest) GetJobCardIndex() int32 {
	if x != nil {
		return x.JobCardIndex
	}
	return 0
}

func (x *SkillPanelUnlockRequest) GetSkillPanelGroupIndex() int32 {
	if x != nil {
		return x.SkillPanelGroupIndex
	}
	return 0
}

func (x *SkillPanelUnlockRequest) GetSkillPanelIndex() int32 {
	if x != nil {
		return x.SkillPanelIndex
	}
	return 0
}

type TeleportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionMap      string                         `protobuf:"bytes,1,opt,name=region_map,json=regionMap,proto3" json:"region_map,omitempty"`
	RegionMapNode  int32                          `protobuf:"varint,2,opt,name=region_map_node,json=regionMapNode,proto3" json:"region_map_node,omitempty"`
	RegionEvents   []*protog.ProtoRegionEvent     `protobuf:"bytes,3,rep,name=region_events,json=regionEvents,proto3" json:"region_events,omitempty"`
	NodeEvents     []*protog.ProtoRegionNodeEvent `protobuf:"bytes,4,rep,name=node_events,json=nodeEvents,proto3" json:"node_events,omitempty"`
	CurrentMapData *protog.ProtoRegionMapInstance `protobuf:"bytes,5,opt,name=current_map_data,json=currentMapData,proto3,oneof" json:"current_map_data,omitempty"`
}

func (x *TeleportResponse) Reset() {
	*x = TeleportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeleportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportResponse) ProtoMessage() {}

func (x *TeleportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportResponse.ProtoReflect.Descriptor instead.
func (*TeleportResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{27}
}

func (x *TeleportResponse) GetRegionMap() string {
	if x != nil {
		return x.RegionMap
	}
	return ""
}

func (x *TeleportResponse) GetRegionMapNode() int32 {
	if x != nil {
		return x.RegionMapNode
	}
	return 0
}

func (x *TeleportResponse) GetRegionEvents() []*protog.ProtoRegionEvent {
	if x != nil {
		return x.RegionEvents
	}
	return nil
}

func (x *TeleportResponse) GetNodeEvents() []*protog.ProtoRegionNodeEvent {
	if x != nil {
		return x.NodeEvents
	}
	return nil
}

func (x *TeleportResponse) GetCurrentMapData() *protog.ProtoRegionMapInstance {
	if x != nil {
		return x.CurrentMapData
	}
	return nil
}

type FetchPendingRegionEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionMapId string                         `protobuf:"bytes,1,opt,name=region_map_id,json=regionMapId,proto3" json:"region_map_id,omitempty"`
	Event       []*protog.ProtoRegionEventData `protobuf:"bytes,2,rep,name=event,proto3" json:"event,omitempty"`
}

func (x *FetchPendingRegionEventsResponse) Reset() {
	*x = FetchPendingRegionEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPendingRegionEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPendingRegionEventsResponse) ProtoMessage() {}

func (x *FetchPendingRegionEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPendingRegionEventsResponse.ProtoReflect.Descriptor instead.
func (*FetchPendingRegionEventsResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{28}
}

func (x *FetchPendingRegionEventsResponse) GetRegionMapId() string {
	if x != nil {
		return x.RegionMapId
	}
	return ""
}

func (x *FetchPendingRegionEventsResponse) GetEvent() []*protog.ProtoRegionEventData {
	if x != nil {
		return x.Event
	}
	return nil
}

type ProcessRegionEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persist bool `protobuf:"varint,1,opt,name=persist,proto3" json:"persist,omitempty"`
}

func (x *ProcessRegionEventResponse) Reset() {
	*x = ProcessRegionEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_response_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessRegionEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRegionEventResponse) ProtoMessage() {}

func (x *ProcessRegionEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_response_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRegionEventResponse.ProtoReflect.Descriptor instead.
func (*ProcessRegionEventResponse) Descriptor() ([]byte, []int) {
	return file_game_response_proto_rawDescGZIP(), []int{29}
}

func (x *ProcessRegionEventResponse) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

var File_game_response_proto protoreflect.FileDescriptor

var file_game_response_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x1a, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x72, 0x61, 0x6e, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4e, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe9, 0x01,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa8, 0x04, 0x0a, 0x16, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x3d,
	0x0a, 0x0c, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x0b, 0x73, 0x65, 0x65, 0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x30, 0x0a,
	0x14, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x12, 0x73, 0x65, 0x65,
	0x64, 0x41, 0x72, 0x65, 0x61, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12,
	0x32, 0x0a, 0x15, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x13,
	0x73, 0x65, 0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x69, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x3f, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x72, 0x6f, 0x70, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x44, 0x72,
	0x6f, 0x70, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x44, 0x0a, 0x12, 0x77, 0x65,
	0x65, 0x6b, 0x6c, 0x79, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x10,
	0x77, 0x65, 0x65, 0x6b, 0x6c, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x42, 0x0a, 0x11, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x61,
	0x6e, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x22, 0x54, 0x0a, 0x14, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x76, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0b,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0b, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0xab, 0x01, 0x0a, 0x13, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x74,
	0x61, 0x6d, 0x69, 0x6e, 0x61, 0x5f, 0x64, 0x65, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x44, 0x65,
	0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x6d, 0x69,
	0x6e, 0x61, 0x5f, 0x64, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x6d, 0x69, 0x6e, 0x61, 0x44, 0x65, 0x63, 0x22, 0x34, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x15,
	0x0a, 0x13, 0x43, 0x61, 0x72, 0x64, 0x41, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x48, 0x0a, 0x15, 0x43, 0x61, 0x72, 0x64, 0x46, 0x61, 0x76,
	0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22,
	0x91, 0x03, 0x0a, 0x12, 0x43, 0x61, 0x72, 0x64, 0x46, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x24,
	0x0a, 0x0e, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x45, 0x78, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x63, 0x63,
	0x75, 0x6d, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x61,
	0x72, 0x64, 0x41, 0x63, 0x63, 0x75, 0x6d, 0x45, 0x78, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65,
	0x65, 0x64, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x67, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x65, 0x65, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x47, 0x61,
	0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x5f, 0x67, 0x61, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x47, 0x61, 0x69, 0x6e,
	0x12, 0x36, 0x0a, 0x17, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x63, 0x61,
	0x72, 0x64, 0x73, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x15, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x62, 0x61, 0x6e, 0x6b,
	0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x3b, 0x0a, 0x0b, 0x66, 0x75, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x66, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x73, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x17, 0x43, 0x61, 0x72, 0x64, 0x42, 0x6f, 0x6f, 0x73,
	0x74, 0x46, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x65, 0x64,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x67, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x73, 0x65, 0x65, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x47, 0x61, 0x69, 0x6e,
	0x12, 0x2c, 0x0a, 0x12, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x5f, 0x67, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x47, 0x61, 0x69, 0x6e, 0x12, 0x3b,
	0x0a, 0x0b, 0x66, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x0a, 0x66, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x10, 0x43,
	0x61, 0x72, 0x64, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x73, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x61, 0x72, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x1a, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x4a, 0x0a, 0x18, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x4f, 0x0a, 0x1b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x41, 0x6c,
	0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4d, 0x0a, 0x19, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x73, 0x22, 0x5c, 0x0a, 0x1d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x7a, 0x0a, 0x13, 0x44, 0x65, 0x63, 0x6b, 0x45, 0x64, 0x69, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x44,
	0x0a, 0x17, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x83, 0x03, 0x0a, 0x17, 0x46, 0x69, 0x72, 0x73, 0x74, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x14, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x64, 0x12, 0x46, 0x0a, 0x0d, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x5f, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0c, 0x64, 0x61,
	0x69, 0x6c, 0x79, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x54, 0x0a, 0x14, 0x73, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x62, 0x6f, 0x6e,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x12, 0x73, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x6f, 0x6e, 0x75, 0x73,
	0x12, 0x52, 0x0a, 0x13, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x11, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42,
	0x6f, 0x6e, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x7b, 0x0a, 0x12, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x56, 0x69, 0x65, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x3b, 0x0a, 0x0a, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x43, 0x61, 0x72,
	0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x0a, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x53, 0x6f, 0x72, 0x74, 0x22, 0x3a, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x74, 0x65,
	0x6d, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9b,
	0x01, 0x0a, 0x17, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x55, 0x6e, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4a, 0x6f,
	0x62, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x32,
	0x0a, 0x14, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x61, 0x6e, 0x65, 0x6c,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0xbb, 0x02, 0x0a,
	0x10, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x70,
	0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x4d, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x4d, 0x0a, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7a, 0x0a, 0x20, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x70,
	0x49, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x42, 0x43,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73,
	0x74, 0x6a, 0x61, 0x63, 0x6b, 0x31, 0x35, 0x32, 0x31, 0x2f, 0x6d, 0x65, 0x76, 0x69, 0x75, 0x6d,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0xaa, 0x02, 0x0c, 0x4d, 0x6f, 0x62, 0x69, 0x75, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_response_proto_rawDescOnce sync.Once
	file_game_response_proto_rawDescData = file_game_response_proto_rawDesc
)

func file_game_response_proto_rawDescGZIP() []byte {
	file_game_response_proto_rawDescOnce.Do(func() {
		file_game_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_response_proto_rawDescData)
	})
	return file_game_response_proto_rawDescData
}

var file_game_response_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_game_response_proto_goTypes = []interface{}{
	(*ApplicationError)(nil),                  // 0: protoc.ApplicationError
	(*Response)(nil),                          // 1: protoc.Response
	(*ResponseHeader)(nil),                    // 2: protoc.ResponseHeader
	(*BattleCompleteResponse)(nil),            // 3: protoc.BattleCompleteResponse
	(*BattleReviveResponse)(nil),              // 4: protoc.BattleReviveResponse
	(*BattleStartResponse)(nil),               // 5: protoc.BattleStartResponse
	(*CreateProfileResponse)(nil),             // 6: protoc.CreateProfileResponse
	(*CardAugmentResponse)(nil),               // 7: protoc.CardAugmentResponse
	(*CardFavouriteResponse)(nil),             // 8: protoc.CardFavouriteResponse
	(*CardFusionResponse)(nil),                // 9: protoc.CardFusionResponse
	(*CardBoostFusionResponse)(nil),           // 10: protoc.CardBoostFusionResponse
	(*CardSaleResponse)(nil),                  // 11: protoc.CardSaleResponse
	(*CardTransferResponse)(nil),              // 12: protoc.CardTransferResponse
	(*ClaimLoginCampaignResponse)(nil),        // 13: protoc.ClaimLoginCampaignResponse
	(*ClaimMailBoxItemResponse)(nil),          // 14: protoc.ClaimMailBoxItemResponse
	(*ClaimAllMailBoxItemResponse)(nil),       // 15: protoc.ClaimAllMailBoxItemResponse
	(*DeleteAllMailboxItemResponse)(nil),      // 16: protoc.DeleteAllMailboxItemResponse
	(*ClaimEventRankingResponse)(nil),         // 17: protoc.ClaimEventRankingResponse
	(*ClaimRentalCardRewardResponse)(nil),     // 18: protoc.ClaimRentalCardRewardResponse
	(*ConfirmDailyMissionResponse)(nil),       // 19: protoc.ConfirmDailyMissionResponse
	(*DeckEditAllResponse)(nil),               // 20: protoc.DeckEditAllResponse
	(*FetchPlayerDataResponse)(nil),           // 21: protoc.FetchPlayerDataResponse
	(*FirstDailyLoginResponse)(nil),           // 22: protoc.FirstDailyLoginResponse
	(*FilterSortResponse)(nil),                // 23: protoc.FilterSortResponse
	(*UpdateProfileResponse)(nil),             // 24: protoc.UpdateProfileResponse
	(*StaminaRestoreResponse)(nil),            // 25: protoc.StaminaRestoreResponse
	(*SkillPanelUnlockRequest)(nil),           // 26: protoc.SkillPanelUnlockRequest
	(*TeleportResponse)(nil),                  // 27: protoc.TeleportResponse
	(*FetchPendingRegionEventsResponse)(nil),  // 28: protoc.FetchPendingRegionEventsResponse
	(*ProcessRegionEventResponse)(nil),        // 29: protoc.ProcessRegionEventResponse
	(*protog.ProtoLastBattleResults)(nil),     // 30: protog.ProtoLastBattleResults
	(*protog.ProtoItemValuePair)(nil),         // 31: protog.ProtoItemValuePair
	(*protog.ProtoAbilityCardInstance)(nil),   // 32: protog.ProtoAbilityCardInstance
	(*protor.ProtoRankingInfo)(nil),           // 33: rank.ProtoRankingInfo
	(*protog.ProtoBattleStartData)(nil),       // 34: protog.ProtoBattleStartData
	(*protog.ProtoMailBoxItem)(nil),           // 35: protog.ProtoMailBoxItem
	(*protog.ProtoPlayerDeckCollection)(nil),  // 36: protog.ProtoPlayerDeckCollection
	(*protog.ProtoGameData)(nil),              // 37: protog.ProtoGameData
	(*protog.ProtoDailyMissionInstance)(nil),  // 38: protog.ProtoDailyMissionInstance
	(*protog.ProtoLoginCampaignInstance)(nil), // 39: protog.ProtoLoginCampaignInstance
	(*protog.ProtoCardFilterSort)(nil),        // 40: protog.ProtoCardFilterSort
	(*protog.ProtoRegionEvent)(nil),           // 41: protog.ProtoRegionEvent
	(*protog.ProtoRegionNodeEvent)(nil),       // 42: protog.ProtoRegionNodeEvent
	(*protog.ProtoRegionMapInstance)(nil),     // 43: protog.ProtoRegionMapInstance
	(*protog.ProtoRegionEventData)(nil),       // 44: protog.ProtoRegionEventData
}
var file_game_response_proto_depIdxs = []int32{
	2,  // 0: protoc.Response.header:type_name -> protoc.ResponseHeader
	30, // 1: protoc.BattleCompleteResponse.Results:type_name -> protog.ProtoLastBattleResults
	31, // 2: protoc.BattleCompleteResponse.seed_rewards:type_name -> protog.ProtoItemValuePair
	31, // 3: protoc.BattleCompleteResponse.item_rewards:type_name -> protog.ProtoItemValuePair
	32, // 4: protoc.BattleCompleteResponse.card_drops:type_name -> protog.ProtoAbilityCardInstance
	33, // 5: protoc.BattleCompleteResponse.weekly_rank_update:type_name -> rank.ProtoRankingInfo
	33, // 6: protoc.BattleCompleteResponse.event_rank_update:type_name -> rank.ProtoRankingInfo
	31, // 7: protoc.BattleReviveResponse.ItemRemoved:type_name -> protog.ProtoItemValuePair
	34, // 8: protoc.BattleStartResponse.BattleStartData:type_name -> protog.ProtoBattleStartData
	31, // 9: protoc.CardFusionResponse.fusion_cost:type_name -> protog.ProtoItemValuePair
	31, // 10: protoc.CardBoostFusionResponse.fusion_cost:type_name -> protog.ProtoItemValuePair
	35, // 11: protoc.ClaimLoginCampaignResponse.claim:type_name -> protog.ProtoMailBoxItem
	35, // 12: protoc.ClaimMailBoxItemResponse.claim:type_name -> protog.ProtoMailBoxItem
	35, // 13: protoc.ClaimAllMailBoxItemResponse.claims:type_name -> protog.ProtoMailBoxItem
	35, // 14: protoc.ClaimEventRankingResponse.claims:type_name -> protog.ProtoMailBoxItem
	31, // 15: protoc.ClaimRentalCardRewardResponse.reward_item:type_name -> protog.ProtoItemValuePair
	36, // 16: protoc.DeckEditAllResponse.Collection:type_name -> protog.ProtoPlayerDeckCollection
	37, // 17: protoc.FetchPlayerDataResponse.data:type_name -> protog.ProtoGameData
	38, // 18: protoc.FirstDailyLoginResponse.daily_mission:type_name -> protog.ProtoDailyMissionInstance
	39, // 19: protoc.FirstDailyLoginResponse.standard_login_bonus:type_name -> protog.ProtoLoginCampaignInstance
	39, // 20: protoc.FirstDailyLoginResponse.special_login_bonus:type_name -> protog.ProtoLoginCampaignInstance
	40, // 21: protoc.FilterSortResponse.FilterSort:type_name -> protog.ProtoCardFilterSort
	41, // 22: protoc.TeleportResponse.region_events:type_name -> protog.ProtoRegionEvent
	42, // 23: protoc.TeleportResponse.node_events:type_name -> protog.ProtoRegionNodeEvent
	43, // 24: protoc.TeleportResponse.current_map_data:type_name -> protog.ProtoRegionMapInstance
	44, // 25: protoc.FetchPendingRegionEventsResponse.event:type_name -> protog.ProtoRegionEventData
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_game_response_proto_init() }
func file_game_response_proto_init() {
	if File_game_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleCompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleReviveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardAugmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardFavouriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardFusionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardBoostFusionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardTransferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimLoginCampaignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimMailBoxItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimAllMailBoxItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAllMailboxItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimEventRankingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimRentalCardRewardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmDailyMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckEditAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPlayerDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FirstDailyLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterSortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaminaRestoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillPanelUnlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeleportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPendingRegionEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_response_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessRegionEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_game_response_proto_msgTypes[27].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_response_proto_goTypes,
		DependencyIndexes: file_game_response_proto_depIdxs,
		MessageInfos:      file_game_response_proto_msgTypes,
	}.Build()
	File_game_response_proto = out.File
	file_game_response_proto_rawDesc = nil
	file_game_response_proto_goTypes = nil
	file_game_response_proto_depIdxs = nil
}
