// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: social.message.proto

package protop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePlayerPresenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Online   uint64 `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *UpdatePlayerPresenceRequest) Reset() {
	*x = UpdatePlayerPresenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPresenceRequest) ProtoMessage() {}

func (x *UpdatePlayerPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPresenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPresenceRequest) Descriptor() ([]byte, []int) {
	return file_social_message_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePlayerPresenceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdatePlayerPresenceRequest) GetOnline() uint64 {
	if x != nil {
		return x.Online
	}
	return 0
}

type UpdatePlayerPresenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePlayerPresenceResponse) Reset() {
	*x = UpdatePlayerPresenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPresenceResponse) ProtoMessage() {}

func (x *UpdatePlayerPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPresenceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPresenceResponse) Descriptor() ([]byte, []int) {
	return file_social_message_proto_rawDescGZIP(), []int{1}
}

type UpdatePlayerPositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RegionMap     string `protobuf:"bytes,2,opt,name=region_map,json=regionMap,proto3" json:"region_map,omitempty"`
	RegionMapNode int32  `protobuf:"varint,3,opt,name=region_map_node,json=regionMapNode,proto3" json:"region_map_node,omitempty"`
}

func (x *UpdatePlayerPositionRequest) Reset() {
	*x = UpdatePlayerPositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPositionRequest) ProtoMessage() {}

func (x *UpdatePlayerPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPositionRequest) Descriptor() ([]byte, []int) {
	return file_social_message_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlayerPositionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdatePlayerPositionRequest) GetRegionMap() string {
	if x != nil {
		return x.RegionMap
	}
	return ""
}

func (x *UpdatePlayerPositionRequest) GetRegionMapNode() int32 {
	if x != nil {
		return x.RegionMapNode
	}
	return 0
}

type UpdatePlayerPositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePlayerPositionResponse) Reset() {
	*x = UpdatePlayerPositionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPositionResponse) ProtoMessage() {}

func (x *UpdatePlayerPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPositionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPositionResponse) Descriptor() ([]byte, []int) {
	return file_social_message_proto_rawDescGZIP(), []int{3}
}

type UpdatePlayerCompanionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId    string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CompanionId string `protobuf:"bytes,2,opt,name=companion_id,json=companionId,proto3" json:"companion_id,omitempty"`
}

func (x *UpdatePlayerCompanionRequest) Reset() {
	*x = UpdatePlayerCompanionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerCompanionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerCompanionRequest) ProtoMessage() {}

func (x *UpdatePlayerCompanionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerCompanionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerCompanionRequest) Descriptor() ([]byte, []int) {
	return file_social_message_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePlayerCompanionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdatePlayerCompanionRequest) GetCompanionId() string {
	if x != nil {
		return x.CompanionId
	}
	return ""
}

type UpdatePlayerCompanionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePlayerCompanionResponse) Reset() {
	*x = UpdatePlayerCompanionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerCompanionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerCompanionResponse) ProtoMessage() {}

func (x *UpdatePlayerCompanionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerCompanionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerCompanionResponse) Descriptor() ([]byte, []int) {
	return file_social_message_proto_rawDescGZIP(), []int{5}
}

var File_social_message_proto protoreflect.FileDescriptor

var file_social_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x52, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x70,
	0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x4d, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73, 0x74, 0x6a, 0x61, 0x63, 0x6b,
	0x31, 0x35, 0x32, 0x31, 0x2f, 0x6d, 0x65, 0x76, 0x69, 0x75, 0x6d, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_social_message_proto_rawDescOnce sync.Once
	file_social_message_proto_rawDescData = file_social_message_proto_rawDesc
)

func file_social_message_proto_rawDescGZIP() []byte {
	file_social_message_proto_rawDescOnce.Do(func() {
		file_social_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_social_message_proto_rawDescData)
	})
	return file_social_message_proto_rawDescData
}

var file_social_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_social_message_proto_goTypes = []interface{}{
	(*UpdatePlayerPresenceRequest)(nil),   // 0: presence.UpdatePlayerPresenceRequest
	(*UpdatePlayerPresenceResponse)(nil),  // 1: presence.UpdatePlayerPresenceResponse
	(*UpdatePlayerPositionRequest)(nil),   // 2: presence.UpdatePlayerPositionRequest
	(*UpdatePlayerPositionResponse)(nil),  // 3: presence.UpdatePlayerPositionResponse
	(*UpdatePlayerCompanionRequest)(nil),  // 4: presence.UpdatePlayerCompanionRequest
	(*UpdatePlayerCompanionResponse)(nil), // 5: presence.UpdatePlayerCompanionResponse
}
var file_social_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_social_message_proto_init() }
func file_social_message_proto_init() {
	if File_social_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_social_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerPresenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerPresenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerPositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerPositionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerCompanionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerCompanionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_social_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_message_proto_goTypes,
		DependencyIndexes: file_social_message_proto_depIdxs,
		MessageInfos:      file_social_message_proto_msgTypes,
	}.Build()
	File_social_message_proto = out.File
	file_social_message_proto_rawDesc = nil
	file_social_message_proto_goTypes = nil
	file_social_message_proto_depIdxs = nil
}
