// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: protoidentity/identity.request.proto

package protoidentity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSinglePlayerIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSinglePlayerIdentityRequest) Reset() {
	*x = GetSinglePlayerIdentityRequest{}
	mi := &file_protoidentity_identity_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSinglePlayerIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSinglePlayerIdentityRequest) ProtoMessage() {}

func (x *GetSinglePlayerIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoidentity_identity_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSinglePlayerIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetSinglePlayerIdentityRequest) Descriptor() ([]byte, []int) {
	return file_protoidentity_identity_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetSinglePlayerIdentityRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetSinglePlayerLoadoutIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DeckIndex     int32                  `protobuf:"varint,2,opt,name=deck_index,json=deckIndex,proto3" json:"deck_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSinglePlayerLoadoutIdentityRequest) Reset() {
	*x = GetSinglePlayerLoadoutIdentityRequest{}
	mi := &file_protoidentity_identity_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSinglePlayerLoadoutIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSinglePlayerLoadoutIdentityRequest) ProtoMessage() {}

func (x *GetSinglePlayerLoadoutIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoidentity_identity_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSinglePlayerLoadoutIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetSinglePlayerLoadoutIdentityRequest) Descriptor() ([]byte, []int) {
	return file_protoidentity_identity_request_proto_rawDescGZIP(), []int{1}
}

func (x *GetSinglePlayerLoadoutIdentityRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetSinglePlayerLoadoutIdentityRequest) GetDeckIndex() int32 {
	if x != nil {
		return x.DeckIndex
	}
	return 0
}

type GetSinglePlayerLoadoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DeckIndex     int32                  `protobuf:"varint,2,opt,name=deck_index,json=deckIndex,proto3" json:"deck_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSinglePlayerLoadoutRequest) Reset() {
	*x = GetSinglePlayerLoadoutRequest{}
	mi := &file_protoidentity_identity_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSinglePlayerLoadoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSinglePlayerLoadoutRequest) ProtoMessage() {}

func (x *GetSinglePlayerLoadoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoidentity_identity_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSinglePlayerLoadoutRequest.ProtoReflect.Descriptor instead.
func (*GetSinglePlayerLoadoutRequest) Descriptor() ([]byte, []int) {
	return file_protoidentity_identity_request_proto_rawDescGZIP(), []int{2}
}

func (x *GetSinglePlayerLoadoutRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetSinglePlayerLoadoutRequest) GetDeckIndex() int32 {
	if x != nil {
		return x.DeckIndex
	}
	return 0
}

type GetMultiPlayerLoadoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DeckIndex     int32                  `protobuf:"varint,2,opt,name=deck_index,json=deckIndex,proto3" json:"deck_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultiPlayerLoadoutRequest) Reset() {
	*x = GetMultiPlayerLoadoutRequest{}
	mi := &file_protoidentity_identity_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultiPlayerLoadoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultiPlayerLoadoutRequest) ProtoMessage() {}

func (x *GetMultiPlayerLoadoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoidentity_identity_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultiPlayerLoadoutRequest.ProtoReflect.Descriptor instead.
func (*GetMultiPlayerLoadoutRequest) Descriptor() ([]byte, []int) {
	return file_protoidentity_identity_request_proto_rawDescGZIP(), []int{3}
}

func (x *GetMultiPlayerLoadoutRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetMultiPlayerLoadoutRequest) GetDeckIndex() int32 {
	if x != nil {
		return x.DeckIndex
	}
	return 0
}

type GetRentalCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRentalCardRequest) Reset() {
	*x = GetRentalCardRequest{}
	mi := &file_protoidentity_identity_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRentalCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalCardRequest) ProtoMessage() {}

func (x *GetRentalCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoidentity_identity_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalCardRequest.ProtoReflect.Descriptor instead.
func (*GetRentalCardRequest) Descriptor() ([]byte, []int) {
	return file_protoidentity_identity_request_proto_rawDescGZIP(), []int{4}
}

func (x *GetRentalCardRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_protoidentity_identity_request_proto protoreflect.FileDescriptor

const file_protoidentity_identity_request_proto_rawDesc = "" +
	"\n" +
	"$protoidentity/identity.request.proto\x12\bidentity\"=\n" +
	"\x1eGetSinglePlayerIdentityRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"c\n" +
	"%GetSinglePlayerLoadoutIdentityRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"deck_index\x18\x02 \x01(\x05R\tdeckIndex\"[\n" +
	"\x1dGetSinglePlayerLoadoutRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"deck_index\x18\x02 \x01(\x05R\tdeckIndex\"Z\n" +
	"\x1cGetMultiPlayerLoadoutRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"deck_index\x18\x02 \x01(\x05R\tdeckIndex\"3\n" +
	"\x14GetRentalCardRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerIdBSZ9github.com/justjack1521/mevium/pkg/genproto/protoidentity\xaa\x02\x15Mobius.Proto.Identityb\x06proto3"

var (
	file_protoidentity_identity_request_proto_rawDescOnce sync.Once
	file_protoidentity_identity_request_proto_rawDescData []byte
)

func file_protoidentity_identity_request_proto_rawDescGZIP() []byte {
	file_protoidentity_identity_request_proto_rawDescOnce.Do(func() {
		file_protoidentity_identity_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoidentity_identity_request_proto_rawDesc), len(file_protoidentity_identity_request_proto_rawDesc)))
	})
	return file_protoidentity_identity_request_proto_rawDescData
}

var file_protoidentity_identity_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protoidentity_identity_request_proto_goTypes = []any{
	(*GetSinglePlayerIdentityRequest)(nil),        // 0: identity.GetSinglePlayerIdentityRequest
	(*GetSinglePlayerLoadoutIdentityRequest)(nil), // 1: identity.GetSinglePlayerLoadoutIdentityRequest
	(*GetSinglePlayerLoadoutRequest)(nil),         // 2: identity.GetSinglePlayerLoadoutRequest
	(*GetMultiPlayerLoadoutRequest)(nil),          // 3: identity.GetMultiPlayerLoadoutRequest
	(*GetRentalCardRequest)(nil),                  // 4: identity.GetRentalCardRequest
}
var file_protoidentity_identity_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoidentity_identity_request_proto_init() }
func file_protoidentity_identity_request_proto_init() {
	if File_protoidentity_identity_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoidentity_identity_request_proto_rawDesc), len(file_protoidentity_identity_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoidentity_identity_request_proto_goTypes,
		DependencyIndexes: file_protoidentity_identity_request_proto_depIdxs,
		MessageInfos:      file_protoidentity_identity_request_proto_msgTypes,
	}.Build()
	File_protoidentity_identity_request_proto = out.File
	file_protoidentity_identity_request_proto_goTypes = nil
	file_protoidentity_identity_request_proto_depIdxs = nil
}
