// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: protomodel/item.proto

package protomodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SysId          string                 `protobuf:"bytes,1,opt,name=sys_id,json=sysId,proto3" json:"sys_id,omitempty"`
	Active         bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Maximum        int32                  `protobuf:"varint,4,opt,name=maximum,proto3" json:"maximum,omitempty"`
	MonthlyMaximum int32                  `protobuf:"varint,5,opt,name=monthly_maximum,json=monthlyMaximum,proto3" json:"monthly_maximum,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaseItem) Reset() {
	*x = BaseItem{}
	mi := &file_protomodel_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseItem) ProtoMessage() {}

func (x *BaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_protomodel_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseItem.ProtoReflect.Descriptor instead.
func (*BaseItem) Descriptor() ([]byte, []int) {
	return file_protomodel_item_proto_rawDescGZIP(), []int{0}
}

func (x *BaseItem) GetSysId() string {
	if x != nil {
		return x.SysId
	}
	return ""
}

func (x *BaseItem) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BaseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseItem) GetMaximum() int32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *BaseItem) GetMonthlyMaximum() int32 {
	if x != nil {
		return x.MonthlyMaximum
	}
	return 0
}

var File_protomodel_item_proto protoreflect.FileDescriptor

const file_protomodel_item_proto_rawDesc = "" +
	"\n" +
	"\x15protomodel/item.proto\x12\x05model\"\x90\x01\n" +
	"\bBaseItem\x12\x15\n" +
	"\x06sys_id\x18\x01 \x01(\tR\x05sysId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\amaximum\x18\x04 \x01(\x05R\amaximum\x12'\n" +
	"\x0fmonthly_maximum\x18\x05 \x01(\x05R\x0emonthlyMaximumB8Z6github.com/justjack1521/mevium/pkg/genproto/protomodelb\x06proto3"

var (
	file_protomodel_item_proto_rawDescOnce sync.Once
	file_protomodel_item_proto_rawDescData []byte
)

func file_protomodel_item_proto_rawDescGZIP() []byte {
	file_protomodel_item_proto_rawDescOnce.Do(func() {
		file_protomodel_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protomodel_item_proto_rawDesc), len(file_protomodel_item_proto_rawDesc)))
	})
	return file_protomodel_item_proto_rawDescData
}

var file_protomodel_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protomodel_item_proto_goTypes = []any{
	(*BaseItem)(nil), // 0: model.BaseItem
}
var file_protomodel_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protomodel_item_proto_init() }
func file_protomodel_item_proto_init() {
	if File_protomodel_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protomodel_item_proto_rawDesc), len(file_protomodel_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protomodel_item_proto_goTypes,
		DependencyIndexes: file_protomodel_item_proto_depIdxs,
		MessageInfos:      file_protomodel_item_proto_msgTypes,
	}.Build()
	File_protomodel_item_proto = out.File
	file_protomodel_item_proto_goTypes = nil
	file_protomodel_item_proto_depIdxs = nil
}
