// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: protomodel/test.request.proto

package protomodel

import (
	protogame "github.com/justjack1521/mevium/pkg/genproto/protogame"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestScenarioBattleSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionNodeId  string                 `protobuf:"bytes,1,opt,name=region_node_id,json=regionNodeId,proto3" json:"region_node_id,omitempty"`
	ScenarioIndex int32                  `protobuf:"varint,2,opt,name=scenario_index,json=scenarioIndex,proto3" json:"scenario_index,omitempty"`
	Seed          int64                  `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestScenarioBattleSelectionRequest) Reset() {
	*x = TestScenarioBattleSelectionRequest{}
	mi := &file_protomodel_test_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestScenarioBattleSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestScenarioBattleSelectionRequest) ProtoMessage() {}

func (x *TestScenarioBattleSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protomodel_test_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestScenarioBattleSelectionRequest.ProtoReflect.Descriptor instead.
func (*TestScenarioBattleSelectionRequest) Descriptor() ([]byte, []int) {
	return file_protomodel_test_request_proto_rawDescGZIP(), []int{0}
}

func (x *TestScenarioBattleSelectionRequest) GetRegionNodeId() string {
	if x != nil {
		return x.RegionNodeId
	}
	return ""
}

func (x *TestScenarioBattleSelectionRequest) GetScenarioIndex() int32 {
	if x != nil {
		return x.ScenarioIndex
	}
	return 0
}

func (x *TestScenarioBattleSelectionRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type TestScenarioBattleSelectionResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Result        *protogame.ProtoBattleSelection `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestScenarioBattleSelectionResponse) Reset() {
	*x = TestScenarioBattleSelectionResponse{}
	mi := &file_protomodel_test_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestScenarioBattleSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestScenarioBattleSelectionResponse) ProtoMessage() {}

func (x *TestScenarioBattleSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protomodel_test_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestScenarioBattleSelectionResponse.ProtoReflect.Descriptor instead.
func (*TestScenarioBattleSelectionResponse) Descriptor() ([]byte, []int) {
	return file_protomodel_test_request_proto_rawDescGZIP(), []int{1}
}

func (x *TestScenarioBattleSelectionResponse) GetResult() *protogame.ProtoBattleSelection {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_protomodel_test_request_proto protoreflect.FileDescriptor

const file_protomodel_test_request_proto_rawDesc = "" +
	"\n" +
	"\x1dprotomodel/test.request.proto\x12\x05model\x1a\x14protogame/data.proto\"\x85\x01\n" +
	"\"TestScenarioBattleSelectionRequest\x12$\n" +
	"\x0eregion_node_id\x18\x01 \x01(\tR\fregionNodeId\x12%\n" +
	"\x0escenario_index\x18\x02 \x01(\x05R\rscenarioIndex\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x03R\x04seed\"Y\n" +
	"#TestScenarioBattleSelectionResponse\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.game.ProtoBattleSelectionR\x06resultB8Z6github.com/justjack1521/mevium/pkg/genproto/protomodelb\x06proto3"

var (
	file_protomodel_test_request_proto_rawDescOnce sync.Once
	file_protomodel_test_request_proto_rawDescData []byte
)

func file_protomodel_test_request_proto_rawDescGZIP() []byte {
	file_protomodel_test_request_proto_rawDescOnce.Do(func() {
		file_protomodel_test_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protomodel_test_request_proto_rawDesc), len(file_protomodel_test_request_proto_rawDesc)))
	})
	return file_protomodel_test_request_proto_rawDescData
}

var file_protomodel_test_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protomodel_test_request_proto_goTypes = []any{
	(*TestScenarioBattleSelectionRequest)(nil),  // 0: model.TestScenarioBattleSelectionRequest
	(*TestScenarioBattleSelectionResponse)(nil), // 1: model.TestScenarioBattleSelectionResponse
	(*protogame.ProtoBattleSelection)(nil),      // 2: game.ProtoBattleSelection
}
var file_protomodel_test_request_proto_depIdxs = []int32{
	2, // 0: model.TestScenarioBattleSelectionResponse.result:type_name -> game.ProtoBattleSelection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protomodel_test_request_proto_init() }
func file_protomodel_test_request_proto_init() {
	if File_protomodel_test_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protomodel_test_request_proto_rawDesc), len(file_protomodel_test_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protomodel_test_request_proto_goTypes,
		DependencyIndexes: file_protomodel_test_request_proto_depIdxs,
		MessageInfos:      file_protomodel_test_request_proto_msgTypes,
	}.Build()
	File_protomodel_test_request_proto = out.File
	file_protomodel_test_request_proto_goTypes = nil
	file_protomodel_test_request_proto_depIdxs = nil
}
