syntax = "proto3";

package multi;

option csharp_namespace = "Mobius.Proto.Multi";
option go_package = "github.com/justjack1521/mevium/pkg/genproto/protomulti";

import "protomulti/multi.proto";

message GetGameResponse {
  ProtoGameSummary game_summary = 1;
}

message GameReadyPlayerResponse {

}

message GameEnqueueActionResponse {

}

message GameDequeueActionResponse {

}

message GameLockActionResponse {

}

message SessionCreateResponse {
}

message SessionEndResponse {

}

message LobbyCreateResponse {
  string lobby_id = 1;
  string party_id = 2;
}

message LobbyCancelResponse {

}

message LobbyReadyResponse {

}

message LobbyStartResponse {
  string game_id = 1;
}

message LobbyStampResponse {

}

message LobbySearchResponse {
  repeated ProtoLobbySummary lobbies = 1;
}

message ParticipantJoinResponse {

}

message ParticipantLeaveResponse {

}

message ParticipantWatchResponse {

}

message ParticipantUnwatchResponse {

}

message ParticipantReadyResponse {

}

message ParticipantFindResponse {

}

message ParticipantUnreadyResponse {

}

message GameHPConsensusResponse {

}

message GameCatchUpResponse {
  uint64 from_sequence    = 1;
  uint64 to_sequence      = 2;
  int64  turn_remaining_ms = 3;
}

message GamePlayerDeathResponse {}

message GamePlayerReviveResponse {}

enum ReviveClaimDenyReason {
  REVIVE_CLAIM_DENY_NONE = 0;
  REVIVE_CLAIM_DENY_TARGET_NOT_FOUND = 1;
  REVIVE_CLAIM_DENY_TARGET_ALIVE = 2;
  REVIVE_CLAIM_DENY_ALREADY_CLAIMED = 3;
  REVIVE_CLAIM_DENY_UNAVAILABLE = 4;
}

message GamePlayerReviveClaimResponse {
  bool                  granted      = 1;
  ReviveClaimDenyReason deny_reason  = 2;
  int64                 remaining_ms = 3;
}